name: StopTramplingMyCrops
version: ${project.version}
main: com.michaelinfernus.stoptramplingmycrops.StopTramplingMyCrops
api-version: 1.13
authors: [MichaelInfernus]
description: Stop players trampling crops in specified worlds
commands:
  stmc:
    description: Admin command for StopTramplingMyCrops
    usage: /stmc <reload/add/remove>
